site_name: Gaming
theme:
  name: readthedocs
  custom_dir: custom/
extra_css:
  - 'stylesheets/extra.css'
repo_url: https://github.com/tjohare/tjohare.github.io/
edit_uri: gaming
site_url: https://tjohare.github.io/gaming
nav:
    - Home: index.md
    - About: about.md
