title: TJ O'Hare Docs Repo
description: This is my personal documentation repository for book concepts I'm working on, REST API standards I've written, and Quality Assurance ideas I've published.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
