site_name: Photography
site_description: Photography stuff
site_author: TJ O'Hare
site_url: https://tjohare.github.io/hotography
copyright: 'Copyright &copy; 2021 TJ OHare'


#Custom
extra_css:
  - 'stylesheets/extra.css'
extra:
  social:
    - icon: fontawesome/brands/facebook-square
      link: https://www.facebook.com/edward.ohare.jr
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gdistortions
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/tjohare/


#Plugins
plugins:
    - search
    - mermaid2
    - macros:
        include_dir: custom
        include_yaml:
          - custom/daimon.yml

#Extra_javascript
extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js
    - javascripts/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#Config
theme:
  name: material
  language: 'en'
  features:
    - navigation.sections
    - navigation.tabs #remove to have everything in the left hand navigation instead...
    - toc.integrate
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  font:
    text: 'Permanent Marker'
    code: 'Architects Daughter'


#Markdowns
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
