theme:
  name: material
  custom_dir: custom/
extra_css:
  - 'stylesheets/extra.css'
markdown_extensions:
  - admonition
  - footnotes
site_name: QA Automation Standards Guide
# site_dir: ../public/share/
# use_directory_urls: false
nav:
  - Introduction: index.md
  - Development Environment and Tools: dev_environment.md
  - Naming Standards and Conventions: naming.md
  - File Organization: file_organization.md
  - Standard Libraries: libraries.md
  - Revision and Version Control Systems: revision_version_control.md
  - Method Visibility: method_visibility.md
  - Headers: headers.md
  - Logging: logging.md
  - Test Order Execution: test_order.md
  - Test categories and criticality: categories_criticality.md
  - Specifications for Error Handling: error_handling.md
  - Miscellaneous Rules for Coding: misc_rules.md
  - Jenkins & Jira integration: jira_jenkins.md
