site_name: Book Ideas
site_url: https://tjohare.github.io/book_ideas
site_description: All Book Ideas
site_author: TJ O'Hare
copyright: 'Copyright &copy; 2021 TJ OHare'

#Custom
extra_css:
  - 'stylesheets/extra.css'
extra:
  social:
    - icon: fontawesome/brands/facebook-square
      link: https://www.facebook.com/edward.ohare.jr
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gdistortions
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/tjohare/

#Plugins
plugins:
    - search
    - mermaid2
    - macros:
        include_yaml:
          - docs/books/daimonic/variables.yml

#Extra_javascript
extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js
    - javascripts/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#Config
#Material Logos can be found here: https://pictogrammers.github.io/@mdi/font/5.4.55/
theme:
  name: material
  language: 'en'
  features:
    - navigation.sections
    - navigation.tabs #remove to have everything in the left hand navigation instead...
    - toc.integrate
  palette:
    primary: 'indigo'
    accent: 'deep purple'
  font:
    text: 'Roboto'
    code: 'Permanent Marker'



#Markdowns
markdown_extensions:
  - meta
  - def_list
  - attr_list
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
